---
deployment:
  tasks:
    # Define the deployment path
    - export DEPLOYPATH=/home/munaimpr/public_html/

    # Copy all files and directories from the project to the deployment path
    - /bin/cp -R * $DEPLOYPATH

    # Change to the deployment directory
    - cd $DEPLOYPATH

    # Install Composer dependencies
    - /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist --optimize-autoloader

    # Set appropriate permissions
    - find storage -type d -exec chmod 755 {} \;
    - find storage -type f -exec chmod 644 {} \;
    - chmod -R 775 bootstrap/cache
    - chmod -R 775 storage

    # Generate application key (if it's not already set)
    - php artisan key:generate --force

    # Run database migrations (if necessary)
    - php artisan migrate --force

    # Clear and cache configuration
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
